format = """
$directory\
$git_branch\
$git_status\
$character"""

add_newline = false

[git_branch]
style = 'fg:red'
symbol = 'ï˜ '
format =  '[$symbol\($branch(:$remote_branch)\)]($style) '

[git_status]
style = 'fg:yellow'
format = '([$all_status$ahead_behind]($style) )'

[docker_context]
disabled = true
